import { Button, EditBox, Label, Layout, Node, ScrollView, instantiate } from 'cc';
import { ProtocolClient } from '../../../Common/Code/Runtime/network/ProtocolClient';
import { LegacyForm, LegacyFormManager } from '../../../Common/Code/Runtime/ui/LegacyFormManager';
import { setClubDynamicLabel } from './ClubDynamicLabel';
import { ScrollEvents } from '../../../Common/Code/UI/UnifiedScroll';

interface ReportPlayer { pid?: number; name?: string; clubName?: string }
interface ReportRow { player?: ReportPlayer; size?: number; winner?: number; roomCard?: number; roomCardSize?: number; clubCard?: number; clubCardSize?: number; point?: number; clubCent?: number }
interface ReportResult { totalPageNum?: number; clubPlayerRoomAloneLogBOS?: ReportRow[] }

export class LegacyClubReportController {
    private form: LegacyForm | null = null; private clubId = 0; private unionId = 0; private roomIDs: number[] = []; private isAll = false; private getType = 0; private showAllClub = false; private page = 1; private pages = 1; private loading = false;
    private readonly disposers: Array<() => void> = []; private readonly rowDisposers: Array<() => void> = [];
    public constructor(private readonly forms: LegacyFormManager, private readonly client: ProtocolClient) {}
    public install(): void { this.forms.register('ui/club/UIClubReport', { zOrder: 10, lifecycle: { onCreate: (form) => this.bind(form), onShow: (form, clubId, roomIDs, isAll, getType, showAllClub, unionId) => this.show(form, Number(clubId ?? 0), this.numbers(roomIDs), Boolean(isAll), Number(getType ?? 0), Boolean(showAllClub), Number(unionId ?? 0)), onClose: () => { this.form = null; this.clearRows(); } }}); }
    public dispose(): void { this.clearRows(); for (const dispose of this.disposers.splice(0)) dispose(); }
    private bind(form: LegacyForm): void { this.click(form.node, 'btn_close', () => this.forms.close('ui/club/UIClubReport')); this.click(form.node, 'btn_search', () => { this.page = 1; void this.load(true); }); this.active(form.node, 'btn_next', false); this.active(form.node, 'btn_last', false); this.active(form.node, 'pageGo', false); this.active(form.node, 'lb_page', false); const scroll = this.desc(form.node, 'layout')?.parent?.parent?.getComponent(ScrollView); if (scroll) this.disposers.push(ScrollEvents.onBottom(scroll, () => { if (!this.loading && this.page < this.pages) { this.page += 1; void this.load(false); } })); }
    private show(form: LegacyForm, clubId: number, roomIDs: number[], isAll: boolean, getType: number, showAllClub: boolean, unionId: number): void { this.form = form; this.clubId = clubId; this.unionId = unionId; this.roomIDs = roomIDs; this.isAll = isAll; this.getType = getType; this.showAllClub = showAllClub; this.page = 1; this.pages = 1; const search = this.desc(form.node, 'editbox')?.getComponent(EditBox); if (search) search.string = ''; void this.load(true); }
    private packet(): Record<string, unknown> { const query = this.form ? this.desc(this.form.node, 'editbox')?.getComponent(EditBox)?.string.trim() ?? '' : ''; const packet: Record<string, unknown> = { clubId: this.clubId, roomIDList: this.isAll ? [] : this.roomIDs, isAll: this.isAll, getType: this.getType, pageNum: this.page, query }; if (this.unionId > 0 && this.showAllClub) packet.unionId = this.unionId; return packet; }
    private async load(refresh: boolean): Promise<void> { if (this.loading) return; this.loading = true; try { const result = await this.client.request<ReportResult>('club.CClubSChoolReport', this.packet()); this.pages = Math.max(1, Number(result.totalPageNum ?? 1)); this.render(result.clubPlayerRoomAloneLogBOS ?? [], refresh); } catch (e) { if (refresh) this.render([], true); await this.tip(e instanceof Error ? e.message : '获取成员汇总失败'); } finally { this.loading = false; } }
    private render(rows: ReportRow[], refresh: boolean): void { const form = this.form; if (!form) return; const content = this.desc(form.node, 'layout'); const demo = this.desc(form.node, 'demo'); if (!content || !demo) return; if (refresh) { this.clearRows(); for (const child of [...content.children]) child.destroy(); } demo.active = false; const seen = new Set(content.children.map((child) => Number(child.name))); for (const row of [...rows].sort((a, b) => Number(b.size ?? 0) - Number(a.size ?? 0))) { const pid = Number(row.player?.pid ?? 0); if (seen.has(pid)) continue; seen.add(pid); const node = instantiate(demo); node.name = String(pid); node.active = true; this.label(node, 'lb_fangka', `钻石：${row.roomCard ?? 0}个/${row.roomCardSize ?? 0}局`); this.label(node, 'lb_quanka', `圈卡：${row.clubCard ?? 0}张/${row.clubCardSize ?? 0}局`); this.label(node, 'lb_canyu', `参    与：${row.size ?? 0}局`); this.label(node, 'lb_yingjia', `大赢家：${row.winner ?? 0}场`); this.label(node, 'lb_ClubCent', row.clubCent === undefined ? '' : `俱乐部积分：${Number(row.clubCent) > 0 ? '+' : ''}${row.clubCent}`); this.label(node, 'lb_clubName', String(row.player?.clubName ?? '')); this.label(node, 'lb_point', `${Number(row.point ?? 0) > 0 ? '+' : ''}${row.point ?? 0}`); this.label(node, 'lb_name', String(row.player?.name ?? '')); this.label(node, 'lb_id', `ID:${pid}`); this.rowClick(node, 'btn_detail', () => { void this.forms.show('ui/club/UIClubRecordUser', this.clubId, this.roomIDs, row, this.isAll, this.getType, this.showAllClub, this.unionId); }); content.addChild(node); } content.getComponent(Layout)?.updateLayout(); }
    private async jump(form: LegacyForm): Promise<void> { const text = this.desc(this.desc(form.node, 'pageGo') ?? form.node, 'pageEditBox')?.getComponent(EditBox)?.string.trim() ?? ''; if (!/^\d+$/.test(text)) { await this.tip('请输入纯数字的页数'); return; } const page = Number(text); if (page < 1 || page > this.pages) { await this.tip('输入的页数超出总页数'); return; } this.page = page; await this.load(); }
    private pageLabel(): void { if (this.form) this.label(this.form.node, 'lb_page', `${this.page}/${this.pages}`); }
    private numbers(value: unknown): number[] { return Array.isArray(value) ? value.map(Number).filter(Number.isFinite) : []; }
    private click(root: Node, name: string, fn: () => void): void { const node = this.desc(root, name); if (!node) return; node.on(Button.EventType.CLICK, fn); this.disposers.push(() => node.off(Button.EventType.CLICK, fn)); }
    private rowClick(root: Node, name: string, fn: () => void): void { const node = this.desc(root, name); if (!node) return; node.on(Button.EventType.CLICK, fn); this.rowDisposers.push(() => node.off(Button.EventType.CLICK, fn)); }
    private clearRows(): void { for (const dispose of this.rowDisposers.splice(0)) dispose(); }
    private desc(root: Node, name: string): Node | null { if (root.name === name) return root; for (const child of root.children) { const result = this.desc(child, name); if (result) return result; } return null; }
    private label(root: Node, name: string, value: string): void { setClubDynamicLabel(this.desc(root, name)?.getComponent(Label) ?? null, name, value); }
    private active(root: Node, name: string, value: boolean): void { const node = this.desc(root, name); if (node) node.active = value; }
    private async tip(message: string): Promise<void> { await this.forms.show('UIMessage_Drift', null, null, message); }
}
