import { Button, EditBox, Label, Layout, Node, instantiate } from 'cc';
import { ProtocolClient } from '../../../Common/Code/Runtime/network/ProtocolClient';
import { LegacyForm, LegacyFormManager } from '../../../Common/Code/Runtime/ui/LegacyFormManager';

interface RecordPlayer { pid?: number; name?: string; point?: number; clubCent?: number; clubName?: string }
interface PersonalRecord { roomID?: number; roomId?: number; roomKey?: string | number; configName?: string; gameType?: number; roomState?: number; endTime?: string | number; roomCard?: number; unionId?: number; roomSportsConsume?: number; playerList?: string | RecordPlayer[] }
interface PlayerSummary { player?: { pid?: number; name?: string }; size?: number; winner?: number; roomCardSize?: number; roomCard?: number; point?: number }

export class LegacyClubRecordUserController {
    private form: LegacyForm | null = null;
    private clubId = 0; private unionId = 0; private pid = 0; private page = 1; private pages = 1; private getType = 0; private isAll = false; private isShowAllClub = false; private roomIDs: number[] = [];
    private readonly disposers: Array<() => void> = []; private readonly rowDisposers: Array<() => void> = [];
    public constructor(private readonly forms: LegacyFormManager, private readonly client: ProtocolClient) {}
    public install(): void { this.forms.register('ui/club/UIClubRecordUser', { zOrder: 10, lifecycle: { onCreate: (form) => this.bind(form), onShow: (form, clubId, roomIDs, playerData, isAll, getType, isShowAllClub, unionId) => this.show(form, Number(clubId ?? 0), this.numbers(roomIDs), this.summary(playerData), Boolean(isAll), Number(getType ?? 0), Boolean(isShowAllClub), Number(unionId ?? 0)), onClose: () => { this.form = null; this.clearRows(); } }}); }
    public dispose(): void { this.clearRows(); for (const dispose of this.disposers.splice(0)) dispose(); }
    private bind(form: LegacyForm): void { this.click(form.node, 'btn_close', () => this.forms.close('ui/club/UIClubRecordUser')); this.click(form.node, 'btn_next', () => { if (this.page < this.pages) { this.page += 1; void this.load(true); } }); this.click(form.node, 'btn_last', () => { if (this.page > 1) { this.page -= 1; void this.load(true); } }); this.click(form.node, 'btn_tz', () => { void this.jump(form); }); this.click(form.node, 'btn_searchroom', () => { void this.search(form); }); }
    private show(form: LegacyForm, clubId: number, roomIDs: number[], playerData: PlayerSummary, isAll: boolean, getType: number, isShowAllClub: boolean, unionId: number): void { this.form = form; this.clubId = clubId; this.unionId = unionId; this.roomIDs = roomIDs; this.isAll = isAll; this.getType = getType; this.isShowAllClub = isShowAllClub; this.pid = Number(playerData.player?.pid ?? 0); this.page = 1; this.pages = 1; this.label(form.node, 'lb_name', String(playerData.player?.name ?? '')); this.label(form.node, 'lb_id', `ID:${this.pid}`); this.label(form.node, 'lb_cayu', `参与:${playerData.size ?? 0}场`); this.label(form.node, 'lb_yingjia', `大赢家:${playerData.winner ?? 0}场`); this.label(form.node, 'lb_fangka', `钻石:${playerData.roomCardSize ?? 0}场/${playerData.roomCard ?? 0}个`); this.label(form.node, 'lb_quanka', ''); this.label(form.node, 'lb_point', String(playerData.point ?? 0)); const pageEdit = this.childEdit(form.node, 'pageGo'); if (pageEdit) pageEdit.string = ''; const roomEdit = this.childEdit(form.node, 'roomGo'); if (roomEdit) roomEdit.string = ''; void this.loadPages(); void this.load(true); }
    private packet(query: string | number = 0): Record<string, unknown> { const packet: Record<string, unknown> = { clubId: this.clubId, pid: this.pid, roomIDList: this.isAll ? [] : this.roomIDs, isAll: this.isAll, getType: this.getType, pageNum: this.page, query }; if (this.unionId > 0 && this.isShowAllClub) packet.unionId = this.unionId; return packet; }
    private async loadPages(): Promise<void> { try { const result = await this.client.request<{ pageNumTotal?: number }>('club.CClubPersonalRecordGetPageNum', this.packet()); this.pages = Math.max(1, Number(result.pageNumTotal ?? 1)); this.pageLabel(); } catch { this.pages = 1; this.pageLabel(); } }
    private async load(refresh: boolean, query: string | number = 0): Promise<void> { try { const rows = await this.client.request<PersonalRecord[]>('club.CClubPersonalRecord', this.packet(query)); this.render(rows, refresh); this.pageLabel(query ? 1 : undefined); } catch (e) { if (refresh) this.render([], true); await this.tip(e instanceof Error ? e.message : '获取个人战绩失败'); } }
    private render(rows: PersonalRecord[], refresh: boolean): void { const form = this.form; if (!form) return; const content = this.desc(form.node, 'layout'); const demo = this.desc(form.node, 'demo'); if (!content || !demo) return; if (refresh) { this.clearRows(); for (const child of [...content.children]) child.destroy(); } demo.active = false; rows.forEach((row, index) => { const node = instantiate(demo); node.name = `record${index}`; node.active = true; const players = this.players(row.playerList); this.label(node, 'room_key', String(row.roomKey ?? '')); this.label(node, 'lb_gameName', row.configName || `游戏${row.gameType ?? ''}`); this.label(node, 'lb_roomState', Number(row.roomState ?? 0) === 1 ? '游戏中' : ''); this.label(node, 'datetime', Number(row.roomState ?? 0) === 1 ? '' : String(row.endTime ?? '')); this.active(node, 'icon_fk', Number(row.roomCard ?? 0) > 0); this.active(node, 'icon_qk', false); this.label(node, 'lb_card', Number(row.roomCard ?? 0) > 0 ? `X${row.roomCard}` : ''); this.active(node, 'icon_ClubCent', Number(row.unionId ?? 0) > 0); this.label(node, 'lb_ClubCent', Number(row.unionId ?? 0) > 0 ? `X${row.roomSportsConsume ?? 0}` : ''); this.renderPlayers(node, players); this.rowClick(node, 'btn_record_info', () => { void this.forms.show('UILobbyRecordResult', Number(row.roomID ?? row.roomId ?? 0), players, Number(row.gameType ?? 0), this.unionId, row.roomKey); }); content.addChild(node); }); content.getComponent(Layout)?.updateLayout(); }
    private renderPlayers(record: Node, players: RecordPlayer[]): void { const layout = this.desc(record, 'user_layout'); const demo = this.desc(record, 'userDemo'); if (!layout || !demo) return; demo.active = false; for (const player of players) { const node = instantiate(demo); node.active = true; this.label(node, 'lb_name', String(player.name ?? '')); this.label(node, 'lb_id', `ID:${player.pid ?? ''}`); this.label(node, 'lb_code', player.clubName !== undefined ? '' : `${player.clubCent !== undefined ? '得分:' : ''}${Number(player.point ?? 0) > 0 ? '+' : ''}${player.point ?? 0}`); this.label(node, 'lb_clubName', player.clubName !== undefined ? `圈:${player.clubName}` : ''); this.active(node, 'lb_code', player.clubName === undefined); this.active(node, 'lb_clubName', player.clubName !== undefined); this.label(node, 'lb_ClubCent', player.clubCent === undefined ? '' : `赛:${Number(player.clubCent) > 0 ? '+' : ''}${player.clubCent}`); layout.addChild(node); } layout.getComponent(Layout)?.updateLayout(); }
    private async jump(form: LegacyForm): Promise<void> { const text = this.childEdit(form.node, 'pageGo')?.string.trim() ?? ''; if (!/^\d+$/.test(text)) { await this.tip('请输入纯数字的页数'); return; } const page = Number(text); if (page < 1 || page > this.pages) { await this.tip('输入的页数超出总页数'); return; } this.page = page; await this.load(true); }
    private async search(form: LegacyForm): Promise<void> { const text = this.childEdit(form.node, 'roomGo')?.string.trim() ?? ''; if (!/^\d+$/.test(text) || Number(text) <= 0) { await this.tip('请输入纯数字的房间号'); return; } this.page = 1; await this.load(true, text); }
    private pageLabel(force?: number): void { const form = this.form; if (form) this.label(form.node, 'lb_page', `${force ?? this.page}/${force ? 1 : this.pages}`); }
    private childEdit(root: Node, parent: string): EditBox | null { return this.desc(this.desc(root, parent) ?? root, 'pageEditBox')?.getComponent(EditBox) ?? null; }
    private summary(value: unknown): PlayerSummary { return value && typeof value === 'object' ? value as PlayerSummary : {}; }
    private numbers(value: unknown): number[] { return Array.isArray(value) ? value.map(Number).filter(Number.isFinite) : []; }
    private players(value: PersonalRecord['playerList']): RecordPlayer[] { if (Array.isArray(value)) return value; try { const rows = JSON.parse(String(value ?? '[]')) as unknown; return Array.isArray(rows) ? rows as RecordPlayer[] : []; } catch { return []; } }
    private click(root: Node, name: string, fn: () => void): void { const node = this.desc(root, name); if (!node) return; node.on(Button.EventType.CLICK, fn); this.disposers.push(() => node.off(Button.EventType.CLICK, fn)); }
    private rowClick(root: Node, name: string, fn: () => void): void { const node = this.desc(root, name); if (!node) return; node.on(Button.EventType.CLICK, fn); this.rowDisposers.push(() => node.off(Button.EventType.CLICK, fn)); }
    private clearRows(): void { for (const dispose of this.rowDisposers.splice(0)) dispose(); }
    private desc(root: Node, name: string): Node | null { if (root.name === name) return root; for (const child of root.children) { const result = this.desc(child, name); if (result) return result; } return null; }
    private label(root: Node, name: string, value: string): void { const label = this.desc(root, name)?.getComponent(Label); if (label) label.string = value; }
    private active(root: Node, name: string, value: boolean): void { const node = this.desc(root, name); if (node) node.active = value; }
    private async tip(message: string): Promise<void> { await this.forms.show('UIMessage_Drift', null, null, message); }
}
