import { Button, Color, EditBox, Label, Node, UITransform } from 'cc';
import type { LegacyFormManager } from '../../../Common/Code/Runtime/ui/LegacyFormManager';
import type { SupportCase } from './SupportCaseClient';
import { SupportCaseClient } from './SupportCaseClient';
import { SupportLiveSessionClient, type SupportLiveSession } from './SupportLiveSessionClient';
import { bindSupportNumberCopy } from './SupportNumberCopyController';

/** Support module surface: each action ends in durable state and an explicit UI callback. */
export class SupportController {
 private root:Node|null=null;private cases:SupportCase[]=[];private session:SupportLiveSession|null=null;private timer=0;private busy=false;private readonly disposers:Array<()=>void>=[];
 public constructor(private readonly forms:LegacyFormManager,private readonly casesApi:SupportCaseClient,private readonly liveApi:SupportLiveSessionClient,private readonly report:(e:unknown)=>void){}
 public async open():Promise<void>{const form=await this.forms.show('UILobbyService');if(!form)return;form.find('Popup/Tag/Close')?.once(Button.EventType.CLICK,()=>this.forms.closeAfterPointer('UILobbyService'));bindSupportNumberCopy(form,this.forms);this.build(form.node);await this.refresh();}
 public destroy():void{if(this.timer)clearTimeout(this.timer);for(const d of this.disposers.splice(0))d();this.liveApi.dispose();this.root=null;}
 private build(host:Node):void{let panel=host.getChildByName('production-support');if(panel){this.root=panel;return;}panel=new Node('production-support');host.addChild(panel);this.root=panel;this.label(panel,'title','客服中心',0,205,26);this.label(panel,'status','正在加载工单…',0,160,20);this.edit(panel,'subject','请简要描述问题',0,105,560);this.edit(panel,'description','请填写问题详情或消息',0,45,560);this.button(panel,'create','提交工单',-210,-30,()=>this.create());this.button(panel,'refresh','刷新状态',-70,-30,()=>this.refresh());this.button(panel,'live','在线客服',80,-30,()=>this.startLive());this.button(panel,'send','发送消息',220,-30,()=>this.send());this.label(panel,'messages','暂无客服消息',0,-115,18);this.button(panel,'withdraw','撤回工单',-85,-190,()=>this.withdraw());this.button(panel,'disconnect','断开会话',85,-190,()=>this.disconnect());}
 private async run(action:()=>Promise<void>):Promise<void>{if(this.busy)return;this.busy=true;this.set('status','处理中…');try{await action();}catch(e){this.set('status',`请求失败：${e instanceof Error?e.message:'请稍后重试'}`);this.root?.emit('support-error',e);this.report(e);}finally{this.busy=false;}}
 private refresh=async():Promise<void>=>this.run(async()=>{this.cases=await this.casesApi.list();this.renderCases();if(this.session){this.session=await this.liveApi.get(this.session.id,this.session.lastMessageId);this.renderSession();}this.schedule();});
 private create=async():Promise<void>=>this.run(async()=>{const subject=this.value('subject'),description=this.value('description');if(!subject||!description)throw new Error('请填写问题标题和详情');const item=await this.casesApi.create('TICKET',subject,description);this.cases=[item,...this.cases];this.renderCases();this.root?.emit('support-case-created',item);});
 private withdraw=async():Promise<void>=>this.run(async()=>{const item=this.cases.find(c=>c.status==='OPEN'||c.status==='IN_REVIEW');if(!item)throw new Error('没有可撤回的工单');const next=await this.casesApi.withdraw(item.id,item.version);this.cases=this.cases.map(c=>c.id===next.id?next:c);this.renderCases();this.root?.emit('support-case-updated',next);});
 private startLive=async():Promise<void>=>this.run(async()=>{const item=this.cases.find(c=>c.status==='OPEN'||c.status==='IN_REVIEW');if(!item)throw new Error('请先提交工单');this.session=await this.liveApi.enqueue(item.id);this.renderSession();this.root?.emit('support-live-updated',this.session);this.schedule();});
 private send=async():Promise<void>=>this.run(async()=>{if(!this.session)throw new Error('请先接入在线客服');const body=this.value('description');if(!body)throw new Error('请输入消息');this.session=await this.liveApi.send(this.session.id,body);this.renderSession();this.root?.emit('support-message-sent',this.session);});
 private disconnect=async():Promise<void>=>this.run(async()=>{if(!this.session)throw new Error('当前没有客服会话');this.session=await this.liveApi.disconnect(this.session.id,this.session.version);this.renderSession();this.root?.emit('support-live-updated',this.session);});
 private schedule():void{if(this.timer)clearTimeout(this.timer);if(!this.root||!this.session||this.session.status==='CLOSED')return;this.timer=setTimeout(()=>void this.refresh(),5000);}
 private renderCases():void{const c=this.cases[0];this.set('status',c?`工单 #${c.id} · ${c.status} · ${c.subject}`:'暂无工单，可直接提交');this.root?.emit('support-cases-refreshed',this.cases);}
 private renderSession():void{if(!this.session)return;const rows=this.session.messages.slice(-5).map(m=>`${m.sender}: ${m.body}`);this.set('messages',`会话 ${this.session.status}${rows.length?'\n'+rows.join('\n'):''}`);}
 private value(name:string):string{return this.root?.getChildByName(name)?.getComponent(EditBox)?.string.trim()??'';}private set(name:string,value:string):void{const l=this.root?.getChildByName(name)?.getComponent(Label);if(l)l.string=value;}
 private label(parent:Node,name:string,text:string,x:number,y:number,size:number):Node{const n=new Node(name);n.setPosition(x,y);n.addComponent(UITransform).setContentSize(620,name==='messages'?130:42);const l=n.addComponent(Label);l.string=text;l.fontSize=size;l.color=Color.WHITE;l.overflow=Label.Overflow.SHRINK;parent.addChild(n);return n;}
 private edit(parent:Node,name:string,placeholder:string,x:number,y:number,width:number):void{const n=new Node(name);n.setPosition(x,y);n.addComponent(UITransform).setContentSize(width,48);const e=n.addComponent(EditBox);e.placeholder=placeholder;e.maxLength=name==='description'?2000:120;parent.addChild(n);}
 private button(parent:Node,name:string,text:string,x:number,y:number,fn:()=>void):void{const n=this.label(parent,name,text,x,y,20);n.getComponent(UITransform)?.setContentSize(125,48);n.addComponent(Button);const cb=():void=>fn();n.on(Button.EventType.CLICK,cb);this.disposers.push(()=>n.off(Button.EventType.CLICK,cb));}
}
