/**
 * 本阶段 25 个新地区的已发布目录身份快照（只读）。
 * 身份来源：Server/tools/room-rule-play-identities.json（gameCode/gameId/playVersion/regionCode/workbookPath/sourceIdentity）。
 * 值集来源：Server/work/generated/room-rules/<地区>跑得快.keys.json 的稳定协议值；禁止手改或自造。
 * 省份 slug 不在此文件落字面量，由 regionCode 经 PdkRegionalRoomProfile 的 PDK_PROVINCE_SLUGS 推导。
 */
import{PDK_BUSINESS_CODES}from'./PdkBusinessCodes';
import type{PdkRoomRuleValue}from'./PdkRegionalRoomProfile';

export type PdkRegionVariantCode='A1_MINIMAL'|'A2_WITH_FOUR'|'A3_WITHOUT_FOUR'|'A4_WITHOUT_BOMB_SETTLEMENT'|'A5_WITHOUT_BOMB_SCORE'|'A6_SPECIAL_STRUCTURE';

export interface PdkRegionIdentity{
 readonly code:string;
 readonly gameId:number;
 readonly playVersion:string;
 readonly regionCode:string;
 readonly localeProvince:string;
 readonly localeCity:string;
 readonly displayName:string;
 readonly workbookPath:string;
 readonly variantCode:PdkRegionVariantCode|null;
 readonly publishedValues:Readonly<Record<string,readonly PdkRoomRuleValue[]>>;
}

/** 族 A：22 个 legacy 等价地区（同一份实现 + 6 个变体）。 */
export const LEGACY_PDK_REGION_IDENTITIES:readonly PdkRegionIdentity[]=[
 {code:PDK_BUSINESS_CODES.WANNIAN,gameId:90007,playVersion:"legacy-equivalent-1",regionCode:"CN-36-11-29",localeProvince:"江西",localeCity:"万年",displayName:"万年跑得快",workbookPath:"Client/docs/开房规则表/跑得快/万年跑得快.xlsx",variantCode:"A1_MINIMAL",publishedValues:{"roundCount":[4,8,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"playRule":["first_round_spade_three_first","every_round_spade_three_first","not_required_four_with_three"],"operationTimeoutSeconds":[-1,180,300],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","same_location_blocked"]}},
 {code:PDK_BUSINESS_CODES.LEPING,gameId:90008,playVersion:"legacy-equivalent-1",regionCode:"CN-36-02-81",localeProvince:"江西",localeCity:"乐平",displayName:"乐平跑得快",workbookPath:"Client/docs/开房规则表/跑得快/乐平跑得快.xlsx",variantCode:"A2_WITH_FOUR",publishedValues:{"roundCount":[8,12,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"playRule":["first_round_spade_three_first","every_round_spade_three_first","may_pass","show_hand","bomb_splittable","triple_ace_max_bomb","heart_ten_bonus","first_play_spade_three_optional","manual_pass","manual_ready","last_card_scoring","no_bomb","triple_ace_bomb","anti_cheat","compete_dealer"],"bombSettlementMode":["max_bomb_to_owner","max_bomb_per_round",0,"count_any_bomb"],"bombScore":["double",10],"fourWithMode":["four_with_one","four_with_two","four_with_three"],"roomSettings":["switch_player_count","dissolve_on_round_trustee","dissolve_after_two_rounds_trustee"],"operationTimeoutSeconds":[-1,180,300,60,30,15],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden","chat_forbidden"]}},
 {code:PDK_BUSINESS_CODES.BOZHOU,gameId:90009,playVersion:"legacy-equivalent-1",regionCode:"CN-34-16",localeProvince:"安徽",localeCity:"亳州",displayName:"亳州跑得快",workbookPath:"Client/docs/开房规则表/跑得快/亳州跑得快.xlsx",variantCode:"A3_WITHOUT_FOUR",publishedValues:{"roundCount":[10,20,30],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"playRule":["first_round_heart_three_first","every_round_heart_three_first","may_pass","show_hand","bomb_splittable","triple_ace_max_bomb","heart_ten_bonus","first_play_heart_three_optional","manual_pass","manual_ready","last_card_scoring","no_bomb","triple_ace_bomb","anti_cheat"],"playMode":["big_run","small_run"],"bombSettlementMode":["max_bomb_to_owner","max_bomb_per_round",0,"count_any_bomb"],"bombScore":["double",10],"roomSettings":["switch_player_count","dissolve_on_round_trustee"],"operationTimeoutSeconds":[-1,180,300,60,30],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden","chat_forbidden"]}},
 {code:PDK_BUSINESS_CODES.YUGAN,gameId:90010,playVersion:"legacy-equivalent-1",regionCode:"CN-36-11-27",localeProvince:"江西",localeCity:"余干",displayName:"余干跑得快",workbookPath:"Client/docs/开房规则表/跑得快/余干跑得快.xlsx",variantCode:"A3_WITHOUT_FOUR",publishedValues:{"roundCount":[6,9,12],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"playRule":["first_round_spade_three_first","every_round_spade_three_first","may_pass","show_hand","bomb_splittable","triple_ace_max_bomb","heart_ten_bonus","first_play_spade_three_optional","manual_pass","manual_ready","last_card_scoring","no_bomb","triple_ace_bomb","anti_cheat"],"bombSettlementMode":["max_bomb_to_owner","max_bomb_per_round",0,"count_any_bomb"],"bombScore":["double",10],"roomSettings":["switch_player_count","dissolve_on_round_trustee"],"trusteePenalty":[5,10,20,50,0],"operationTimeoutSeconds":[-1,180,300,60,30],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden","chat_forbidden"]}},
 {code:PDK_BUSINESS_CODES.JIAN,gameId:90011,playVersion:"legacy-equivalent-1",regionCode:"CN-36-08",localeProvince:"江西",localeCity:"吉安",displayName:"吉安跑得快",workbookPath:"Client/docs/开房规则表/跑得快/吉安跑得快.xlsx",variantCode:"A2_WITH_FOUR",publishedValues:{"roundCount":[8,10,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"playRule":["first_round_spade_three_first","every_round_spade_three_first","may_pass","show_hand","bomb_splittable","triple_ace_max_bomb","heart_ten_bonus","first_play_spade_three_optional","manual_pass","manual_ready","last_card_scoring","no_bomb","triple_ace_bomb","anti_cheat","match_score_floor_zero","win_current_score_only"],"bombSettlementMode":["max_bomb_to_owner","max_bomb_per_round",0,"count_any_bomb"],"bombScore":["double",10],"fourWithMode":["four_with_one","four_with_two","four_with_three"],"roomSettings":["switch_player_count","dissolve_on_round_trustee","dissolve_after_two_rounds_trustee"],"operationTimeoutSeconds":[-1,180,300,60,30],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden","chat_forbidden"]}},
 {code:PDK_BUSINESS_CODES.GUSHI,gameId:90012,playVersion:"legacy-equivalent-1",regionCode:"CN-41-15-25",localeProvince:"河南",localeCity:"固始",displayName:"固始跑得快",workbookPath:"Client/docs/开房规则表/跑得快/固始跑得快.xlsx",variantCode:"A4_WITHOUT_BOMB_SETTLEMENT",publishedValues:{"roundCount":[8,10,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"firstPlayRule":["first_round_heart_three_first","every_round_heart_three_first"],"playRule":["show_hand","bomb_splittable","manual_pass","last_card_scoring"],"bombScore":["double",10],"roomSettings":["switch_player_count","dissolve_on_round_trustee"],"operationTimeoutSeconds":[-1,180,300,60,30],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden","chat_forbidden"]}},
 {code:PDK_BUSINESS_CODES.XIAOGAN,gameId:90013,playVersion:"legacy-equivalent-1",regionCode:"CN-42-09",localeProvince:"湖北",localeCity:"孝感",displayName:"孝感跑得快",workbookPath:"Client/docs/开房规则表/跑得快/孝感跑得快.xlsx",variantCode:"A3_WITHOUT_FOUR",publishedValues:{"roundCount":[8,10,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"playRule":["first_round_spade_three_first","every_round_spade_three_first","may_pass","show_hand","bomb_splittable","triple_ace_max_bomb","heart_ten_bonus","first_play_spade_three_optional","manual_pass","manual_ready","last_card_scoring","no_bomb","triple_ace_bomb","anti_cheat"],"piaoMode":["no_piao","piao_custom",1,2],"piaoRounds":["first_round_only","every_round"],"bombSettlementMode":["max_bomb_to_owner","max_bomb_per_round",0,"count_any_bomb"],"bombScore":["double",10],"roomSettings":["switch_player_count","dissolve_on_round_trustee"],"operationTimeoutSeconds":[-1,180,300,60,30],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden","chat_forbidden"]}},
 {code:PDK_BUSINESS_CODES.NINGDU,gameId:90014,playVersion:"legacy-equivalent-1",regionCode:"CN-36-07-30",localeProvince:"江西",localeCity:"宁都",displayName:"宁都跑得快",workbookPath:"Client/docs/开房规则表/跑得快/宁都跑得快.xlsx",variantCode:"A2_WITH_FOUR",publishedValues:{"roundCount":[8,10,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"playRule":["may_pass","show_hand","bomb_splittable","triple_ace_max_bomb","heart_ten_bonus","manual_pass","manual_ready","last_card_scoring","no_bomb","triple_ace_bomb","anti_cheat","match_score_floor_zero","win_current_score_only"],"bombSettlementMode":["max_bomb_to_owner","max_bomb_per_round",0,"count_any_bomb"],"bombScore":["double",10],"fourWithMode":["four_with_one","four_with_two","four_with_three"],"roomSettings":["switch_player_count","dissolve_on_round_trustee","dissolve_after_two_rounds_trustee"],"operationTimeoutSeconds":[-1,180,300,60,30],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden","chat_forbidden"]}},
 {code:PDK_BUSINESS_CODES.HUAIHUA,gameId:90015,playVersion:"legacy-equivalent-1",regionCode:"CN-43-12",localeProvince:"湖南",localeCity:"怀化",displayName:"怀化跑得快",workbookPath:"Client/docs/开房规则表/跑得快/怀化跑得快.xlsx",variantCode:"A3_WITHOUT_FOUR",publishedValues:{"roundCount":[8,10,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"playRule":["first_round_spade_three_first","every_round_spade_three_first","may_pass","show_hand","bomb_splittable","triple_ace_max_bomb","heart_ten_bonus","first_play_spade_three_optional","manual_pass","last_card_scoring","no_bomb","triple_ace_bomb","anti_cheat","random_first_play","match_score_floor_zero","win_carried_only"],"bombSettlementMode":["max_bomb_to_owner","max_bomb_per_round",0,"count_any_bomb"],"bombScore":["double",10],"cutCardScore":["no_cut",0.1,0.2,0.5,0.8,1],"bigRoundScoring":["normal","floor_ten","double_below_ten"],"roomSettings":["switch_player_count","auto_ready","dissolve_on_round_trustee","dissolve_limit_5","dissolve_limit_3","dissolve_after_three_rounds_trustee"],"operationTimeoutSeconds":[-1,180,300,60,30],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden","chat_forbidden"]}},
 {code:PDK_BUSINESS_CODES.XINXIAN,gameId:90016,playVersion:"legacy-equivalent-1",regionCode:"CN-41-15-23",localeProvince:"河南",localeCity:"新县",displayName:"新县跑得快",workbookPath:"Client/docs/开房规则表/跑得快/新县跑得快.xlsx",variantCode:"A2_WITH_FOUR",publishedValues:{"roundCount":[8,10,16],"playerCount":[2,3,4],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"playRule":["first_round_heart_three_first","every_round_heart_three_first","may_pass","show_hand","bomb_splittable","triple_ace_max_bomb","heart_ten_bonus","first_play_heart_three_optional","manual_pass","manual_ready","no_bomb","triple_ace_bomb","anti_cheat","spring","anti_spring"],"bombSettlementMode":["max_bomb_to_owner","max_bomb_per_round",0,"count_any_bomb"],"bombScore":["double",10],"fourWithMode":["four_with_one","four_with_two","four_with_three"],"roomSettings":["switch_player_count","dissolve_on_round_trustee"],"operationTimeoutSeconds":[-1,180,300,60,30],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden","chat_forbidden"]}},
 {code:PDK_BUSINESS_CODES.JINGDEZHEN,gameId:90017,playVersion:"legacy-equivalent-1",regionCode:"CN-36-02",localeProvince:"江西",localeCity:"景德镇",displayName:"景德镇跑得快",workbookPath:"Client/docs/开房规则表/跑得快/景德镇跑得快.xlsx",variantCode:"A5_WITHOUT_BOMB_SCORE",publishedValues:{"roundCount":[8,12,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"playRule":["first_round_spade_three_first","every_round_spade_three_first","not_required","show_hand","bomb_splittable","triple_ace_max_bomb","heart_ten_bonus","first_play_spade_three_optional","manual_pass","auto_ready"],"bombSettlementMode":["count_any_bomb","winner_only",0],"roomSettings":["switch_player_count"],"operationTimeoutSeconds":[-1,180,300,60,30],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden"]}},
 {code:PDK_BUSINESS_CODES.JIANGSU,gameId:90018,playVersion:"legacy-equivalent-1",regionCode:"CN-32",localeProvince:"江苏",localeCity:"江苏",displayName:"江苏跑得快",workbookPath:"Client/docs/开房规则表/跑得快/江苏跑得快.xlsx",variantCode:"A6_SPECIAL_STRUCTURE",publishedValues:{"roundCount":[8,10,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"playRule":["first_round_spade_three_first","every_round_spade_three_first","may_pass","show_hand","bomb_splittable","triple_ace_max_bomb","heart_ten_bonus","first_play_spade_three_optional","manual_pass","manual_ready","last_card_scoring","no_bomb","triple_ace_bomb","anti_cheat"],"fourWithMode":["four_with_one","four_with_two","four_with_three"],"threeWithMode":["triple_with_one","triple_with_two","triple_with_pair"],"capMode":["no_cap","cap_20","cap_60","cap_100","cap_200"],"bombSettlementMode":["max_bomb_to_owner","max_bomb_per_round",0,"count_any_bomb"],"bombScore":["double",10],"roomSettings":["switch_player_count"],"operationTimeoutSeconds":[-1,180,300,60,30],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden","chat_forbidden"]}},
 {code:PDK_BUSINESS_CODES.HENAN,gameId:90019,playVersion:"legacy-equivalent-1",regionCode:"CN-41",localeProvince:"河南",localeCity:"河南",displayName:"河南跑得快",workbookPath:"Client/docs/开房规则表/跑得快/河南跑得快.xlsx",variantCode:"A3_WITHOUT_FOUR",publishedValues:{"roundCount":[8,10,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"firstPlayMode":["first_round_heart_three_required","every_round_heart_three_required","first_round_heart_three_optional","every_round_heart_three_optional"],"playRule":["anti_cheat","heart_ten_bonus","must_beat_with_big","must_beat_on_run","auto_pass","show_hand","last_card_scoring","allow_triple_with_one","allow_triple_with_two","allow_triple_with_pair","allow_four_with_one","allow_four_with_two","allow_four_with_three","auto_ready"],"aceThreeBombMode":["ace_three_max_bomb","ace_three_min_bomb","ace_three_not_bomb"],"bombSettlementMode":["count_any_bomb","max_bomb_per_round",0,"max_bomb_to_owner"],"bombScore":["double",10],"roomSettings":["switch_player_count"],"operationTimeoutSeconds":[-1,180,300,60,30],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden"]}},
 {code:PDK_BUSINESS_CODES.TAIZHOU,gameId:90020,playVersion:"legacy-equivalent-1",regionCode:"CN-32-12",localeProvince:"江苏",localeCity:"泰州",displayName:"泰州跑得快",workbookPath:"Client/docs/开房规则表/跑得快/泰州跑得快.xlsx",variantCode:"A3_WITHOUT_FOUR",publishedValues:{"roundCount":[8,10,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[16],"playRule":["every_round_heart_three_first","winner_first","loser_first","may_pass","show_hand","bomb_splittable","triple_ace_max_bomb","manual_pass","manual_ready","no_bomb","triple_ace_bomb","anti_cheat","match_score_floor_zero","win_current_score_only","bomb_with_one","small_gate"],"reportScoreMode":["score_reported","no_score"],"bombSettlementMode":["max_bomb_per_round",0],"bombScore":[10,5],"straightLengthMode":["five_or_more","six_or_more"],"roomSettings":["switch_player_count","dissolve_on_round_trustee","dissolve_after_two_rounds_trustee"],"operationTimeoutSeconds":[-1,180,300,60,30,15,600],"roomTimeLimitMinutes":[-1,8,10,12,15,20],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden","chat_forbidden"]}},
 {code:PDK_BUSINESS_CODES.HUAIBIN,gameId:90021,playVersion:"legacy-equivalent-1",regionCode:"CN-41-15-27",localeProvince:"河南",localeCity:"淮滨",displayName:"淮滨跑得快",workbookPath:"Client/docs/开房规则表/跑得快/淮滨跑得快.xlsx",variantCode:"A1_MINIMAL",publishedValues:{"roundCount":[8,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"firstPlayRule":["first_round_heart_three_first","every_round_heart_three_first"],"playRule":["show_hand"],"bombScore":["double",10],"roomRestriction":["same_ip_blocked","same_location_blocked"]}},
 {code:PDK_BUSINESS_CODES.HUANGCHUAN,gameId:90022,playVersion:"legacy-equivalent-1",regionCode:"CN-41-15-26",localeProvince:"河南",localeCity:"潢川",displayName:"潢川跑得快",workbookPath:"Client/docs/开房规则表/跑得快/潢川跑得快.xlsx",variantCode:"A6_SPECIAL_STRUCTURE",publishedValues:{"roundCount":[8,10,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"firstPlayRule":["first_round_heart_three_first","every_round_heart_three_first"],"threeWithMode":["triple_with_one","triple_with_pair"],"aceThreeBombMode":["ace_three_max_bomb","ace_three_min_bomb","ace_three_not_bomb"],"playRule":["show_hand","bomb_splittable","manual_pass","last_card_scoring","not_required_beat","keep_three_door_double"],"bombScore":[10],"roomSettings":["switch_player_count","dissolve_on_round_trustee","dissolve_limit_5","dissolve_after_two_rounds_trustee","dissolve_limit_3"],"operationTimeoutSeconds":[-1,180,300,60,30],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden","chat_forbidden"]}},
 {code:PDK_BUSINESS_CODES.POYANG,gameId:90023,playVersion:"legacy-equivalent-1",regionCode:"CN-36-11-28",localeProvince:"江西",localeCity:"鄱阳",displayName:"鄱阳跑得快",workbookPath:"Client/docs/开房规则表/跑得快/鄱阳跑得快.xlsx",variantCode:"A5_WITHOUT_BOMB_SCORE",publishedValues:{"roundCount":[8,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"playRule":["first_round_spade_three_first","every_round_spade_three_first","not_required","show_hand","bomb_splittable","triple_ace_max_bomb","heart_ten_bonus","first_play_spade_three_optional","auto_ready","dissolve_on_round_trustee"],"bombSettlementMode":["count_any_bomb","winner_only",0],"roomSettings":["switch_player_count"],"operationTimeoutSeconds":[-1,180,300,60,30],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden","chat_forbidden"]}},
 {code:PDK_BUSINESS_CODES.JINTAN,gameId:90024,playVersion:"legacy-equivalent-1",regionCode:"CN-32-04-13",localeProvince:"江苏",localeCity:"金坛",displayName:"金坛跑得快",workbookPath:"Client/docs/开房规则表/跑得快/金坛跑得快.xlsx",variantCode:"A2_WITH_FOUR",publishedValues:{"roundCount":[8,10,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"playRule":["first_round_spade_three_first","every_round_spade_three_first","may_pass","show_hand","bomb_splittable","triple_ace_max_bomb","heart_ten_bonus","first_play_spade_three_optional","manual_pass","manual_ready","last_card_scoring","no_bomb","triple_ace_bomb","anti_cheat","match_score_floor_zero","win_current_score_only","four_with_one_is_bomb"],"bombSettlementMode":["max_bomb_to_owner","max_bomb_per_round",0,"count_any_bomb"],"bombScore":["double",10,5],"fourWithMode":["four_with_one","four_with_two"],"roomSettings":["switch_player_count","dissolve_on_round_trustee","dissolve_after_two_rounds_trustee"],"operationTimeoutSeconds":[-1,180,300,60,30,15],"roomTimeLimitMinutes":[-1,8,10,12,15,20],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden","chat_forbidden"]}},
 {code:PDK_BUSINESS_CODES.GAOAN,gameId:90025,playVersion:"legacy-equivalent-1",regionCode:"CN-36-09-83",localeProvince:"江西",localeCity:"高安",displayName:"高安跑得快",workbookPath:"Client/docs/开房规则表/跑得快/高安跑得快.xlsx",variantCode:"A2_WITH_FOUR",publishedValues:{"roundCount":[8,10,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"playRule":["first_round_spade_three_first","every_round_spade_three_first","may_pass","show_hand","bomb_splittable","triple_ace_max_bomb","heart_ten_bonus","first_play_spade_three_optional","manual_pass","manual_ready","last_card_scoring","no_bomb","triple_ace_bomb","anti_cheat","match_score_floor_zero","win_current_score_only"],"bombSettlementMode":["max_bomb_to_owner","max_bomb_per_round",0,"count_any_bomb"],"bombScore":["double",10],"fourWithMode":["four_with_one","four_with_two","four_with_three"],"roomSettings":["switch_player_count","dissolve_on_round_trustee","dissolve_after_two_rounds_trustee","trustee_three_times_irrevocable"],"operationTimeoutSeconds":[-1,180,300,60,30,15],"roomTimeLimitMinutes":[-1,8,10,12,15,20],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden","chat_forbidden"]}},
 {code:PDK_BUSINESS_CODES.YIXING,gameId:90026,playVersion:"legacy-equivalent-1",regionCode:"CN-32-02-82",localeProvince:"江苏",localeCity:"宜兴",displayName:"宜兴跑得快",workbookPath:"Client/docs/开房规则表/跑得快/宜兴跑得快.xlsx",variantCode:"A2_WITH_FOUR",publishedValues:{"roundCount":[8,10,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"playRule":["first_round_spade_three_first","every_round_spade_three_first","may_pass","show_hand","bomb_splittable","triple_ace_max_bomb","heart_ten_bonus","first_play_spade_three_optional","manual_pass","manual_ready","last_card_scoring","no_bomb","triple_ace_bomb","anti_cheat","match_score_floor_zero","win_current_score_only"],"bombSettlementMode":["max_bomb_to_owner","max_bomb_per_round",0,"count_any_bomb"],"bombScore":["double",10],"fourWithMode":["four_with_one","four_with_two","four_with_three"],"piaoMode":["no_piao","piao_custom",1,2,5],"piaoRounds":["first_round_only","every_round"],"roomSettings":["switch_player_count","dissolve_on_round_trustee","dissolve_after_two_rounds_trustee"],"operationTimeoutSeconds":[-1,180,300,60,30],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden","chat_forbidden"]}},
 {code:PDK_BUSINESS_CODES.XUANCHENG,gameId:90027,playVersion:"legacy-equivalent-1",regionCode:"CN-34-18",localeProvince:"安徽",localeCity:"宣城",displayName:"宣城跑得快",workbookPath:"Client/docs/开房规则表/跑得快/宣城跑得快.xlsx",variantCode:"A4_WITHOUT_BOMB_SETTLEMENT",publishedValues:{"roundCount":[8,10,16],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"playRule":["first_round_heart_three_first","may_pass","show_hand","bomb_splittable","triple_ace_max_bomb","manual_pass","manual_ready","last_card_scoring","triple_ace_bomb","anti_cheat","match_score_floor_zero","win_current_score_only"],"bombScore":[5,10,0],"roomSettings":["switch_player_count","dissolve_on_round_trustee","dissolve_after_two_rounds_trustee"],"operationTimeoutSeconds":[-1,180,300,60,30,15],"roomTimeLimitMinutes":[-1,8,10,12,15,20],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","within_100m_blocked","items_forbidden","within_200m_blocked","kick_unready_30s","voice_forbidden","chat_forbidden"]}},
 {code:PDK_BUSINESS_CODES.FUZHOU,gameId:90028,playVersion:"legacy-equivalent-1",regionCode:"CN-36-10",localeProvince:"江西",localeCity:"抚州",displayName:"抚州跑得快",workbookPath:"Client/docs/开房规则表/跑得快/抚州跑得快.xlsx",variantCode:"A4_WITHOUT_BOMB_SETTLEMENT",publishedValues:{"roundCount":[8,16,24],"playerCount":[2,3],"paymentMode":["owner_pays","split_pays","winner_pays"],"dealCardCount":[15,16],"baseScore":[1,2,5,10],"playRule":["must_beat","winner_first","must_beat_on_run","auto_pass","show_hand","last_card_scoring","four_with_three"],"bombScore":[0,5,10],"roomSettings":["switch_player_count"],"operationTimeoutSeconds":[-1,180,300,60,30],"dissolveTimeoutSeconds":[30,60,180,300,-1],"roomRestriction":["same_ip_blocked","same_location_blocked","items_forbidden"]}}
];

/** 族 B/C/D：冕宁、安岳、攀枝花，各有独立规则族。 */
export const NEW_FAMILY_PDK_REGION_IDENTITIES:readonly PdkRegionIdentity[]=[
 {code:PDK_BUSINESS_CODES.MIANNING,gameId:631,playVersion:"mn201-v1.0.0",regionCode:"CN-51-34-33",localeProvince:"四川",localeCity:"冕宁",displayName:"冕宁跑得快",workbookPath:"Client/docs/开房规则表/跑得快/冕宁跑得快.xlsx",variantCode:null,publishedValues:{"playerCount":[2,3],"cardsPerPlayer":[13],"roundCount":[8,12,16],"robDealerRule":["rob_dealer","first_round_no_compete","dealer_cannot_rob_when_idle_pass"],"bombScore":["no_multiplier",1,"unlimited_multiplier"],"rule_mn201_0001":["option_0001"],"roomRestriction":["ip_limit","gps_limit","timeout_auto_play","distance_warning","interaction_forbidden","chat_muted"],"hostingMissThreshold":[3,4,5]}},
 {code:PDK_BUSINESS_CODES.ANYUE,gameId:632,playVersion:"ay201-v1.0.0",regionCode:"CN-51-20-21",localeProvince:"四川",localeCity:"安岳",displayName:"安岳跑得快",workbookPath:"Client/docs/开房规则表/跑得快/安岳跑得快.xlsx",variantCode:null,publishedValues:{"playerCount":[2,3],"roundCount":[8,12,16],"operationTimeoutSeconds":[10,15,20],"deckRange":["cut_40"],"firstPlayRule":["spade_five_first"],"requiredFirstCardRule":["first_round_spade_five_required"],"tripleWithTwoMode":["two_cards_no_compare","two_cards_compare"],"planeWithTwoMode":["two_cards_no_compare","two_cards_compare"],"bombScore":[5,10,20],"rule_ay201_0001":["option_0001"],"playRule":["three_no_attachment","plane_no_attachment","four_with_two","triple_ace_bomb","four_threes_direct_win","triple_ace_plus_two_direct_win"],"hostingMissThreshold":[3,4,5],"roomRestriction":["ip_limit","gps_limit","timeout_auto_play","distance_warning","interaction_forbidden","chat_muted"]}},
 {code:PDK_BUSINESS_CODES.PANZHIHUA,gameId:90006,playVersion:"pz201-v1.0.0",regionCode:"CN-51-04",localeProvince:"四川",localeCity:"攀枝花",displayName:"攀枝花跑得快",workbookPath:"Client/docs/开房规则表/跑得快/攀枝花跑得快.xlsx",variantCode:null,publishedValues:{"playerCount":[2,3,4],"cardsPerPlayer":[10],"roundCount":[8,12,16],"operationTimeoutSeconds":[10,15,30,60],"requiredFirstCardRule":["first_round_spade_five_then_winner"],"bombScore":[10,20,30],"specialPatternScore":[5,10],"rule_pz201_0001":["option_0001"],"playRule":["all_singles","all_pairs","all_black","all_red","all_big","all_small","triple_five_to_ace_bomb"],"hostingMissThreshold":[3,4,5],"roomRestriction":["ip_limit","gps_limit","distance_warning","interaction_forbidden","chat_muted"]}}
];

export const NEW_PDK_REGION_IDENTITIES:readonly PdkRegionIdentity[]=[
 ...LEGACY_PDK_REGION_IDENTITIES,...NEW_FAMILY_PDK_REGION_IDENTITIES
];
