/** Stable business identities for the single PDK family. */
export const PDK_BUSINESS_CODES={
 CHENGDU:'CD201',NEIJIANG:'NJ201',LIANGSHAN:'LS201',
 MIANNING:'MN201',ANYUE:'AY201',PANZHIHUA:'PZ201',
 WANNIAN:'WN201',LEPING:'LP201',BOZHOU:'BZ201',YUGAN:'YG201',JIAN:'JA201',GUSHI:'GS201',
 XIAOGAN:'XG201',NINGDU:'ND201',HUAIHUA:'HH201',XINXIAN:'XX201',JINGDEZHEN:'JD201',JIANGSU:'JS201',
 HENAN:'HN201',TAIZHOU:'TZ201',HUAIBIN:'HB201',HUANGCHUAN:'HC201',POYANG:'PY201',JINTAN:'JT201',
 GAOAN:'GA201',YIXING:'YX201',XUANCHENG:'XC201',FUZHOU:'FZ201'}as const;
export type PdkBusinessCode=typeof PDK_BUSINESS_CODES[keyof typeof PDK_BUSINESS_CODES];

/** 全部规范地区业务编码（既有三地 + 本阶段 25 地，插入顺序固定）。 */
export const PDK_BUSINESS_CODE_LIST:readonly string[]=Object.freeze(Object.values(PDK_BUSINESS_CODES));

/** 既有三地：成都/内江/凉山。 */
export const EXISTING_PDK_BUSINESS_CODES:readonly string[]=Object.freeze([
 PDK_BUSINESS_CODES.CHENGDU,PDK_BUSINESS_CODES.NEIJIANG,PDK_BUSINESS_CODES.LIANGSHAN
]);

/** 本阶段新增的 25 个地区（不含既有三地）。 */
export const NEW_PDK_BUSINESS_CODES:readonly string[]=Object.freeze([
 PDK_BUSINESS_CODES.MIANNING,PDK_BUSINESS_CODES.ANYUE,PDK_BUSINESS_CODES.PANZHIHUA,
 PDK_BUSINESS_CODES.WANNIAN,PDK_BUSINESS_CODES.LEPING,PDK_BUSINESS_CODES.BOZHOU,
 PDK_BUSINESS_CODES.YUGAN,PDK_BUSINESS_CODES.JIAN,PDK_BUSINESS_CODES.GUSHI,
 PDK_BUSINESS_CODES.XIAOGAN,PDK_BUSINESS_CODES.NINGDU,PDK_BUSINESS_CODES.HUAIHUA,
 PDK_BUSINESS_CODES.XINXIAN,PDK_BUSINESS_CODES.JINGDEZHEN,PDK_BUSINESS_CODES.JIANGSU,
 PDK_BUSINESS_CODES.HENAN,PDK_BUSINESS_CODES.TAIZHOU,PDK_BUSINESS_CODES.HUAIBIN,
 PDK_BUSINESS_CODES.HUANGCHUAN,PDK_BUSINESS_CODES.POYANG,PDK_BUSINESS_CODES.JINTAN,
 PDK_BUSINESS_CODES.GAOAN,PDK_BUSINESS_CODES.YIXING,PDK_BUSINESS_CODES.XUANCHENG,
 PDK_BUSINESS_CODES.FUZHOU
]);

const PDK_BUSINESS_CODE_SET:ReadonlySet<string>=new Set(Object.values(PDK_BUSINESS_CODES));
const NEW_PDK_BUSINESS_CODE_SET:ReadonlySet<string>=new Set(NEW_PDK_BUSINESS_CODES);
export function isPdkBusinessCode(value:string):value is PdkBusinessCode{
 return PDK_BUSINESS_CODE_SET.has(value);
}
export function isNewPdkBusinessCode(value:string):boolean{
 return NEW_PDK_BUSINESS_CODE_SET.has(value.trim());
}
