import { Button, Color, isValid, Label, Node, UITransform } from 'cc';
import { CompetitionGateway, type CompetitionEvent, type MatchSnapshot, type Tournament } from '../../../Common/Code/Runtime/Competition/CompetitionGateway';

type UiState='IDLE'|'LOADING'|'QUEUEING'|'WAITING'|'MATCHED'|'CONFIRMING'|'READY'|'CANCELLING'|'CANCELLED'|'TIMED_OUT'|'RECOVERING'|'ERROR';

/** Production lobby UI. Polling consumes the durable JDBC event stream, so reconnects do not lose match/room transitions. */
export class CompetitionController {
  private panel:Node|null=null;private statusLabel:Label|null=null;private tournamentLabel:Label|null=null;private state:UiState='IDLE';private gameId=629;private cursor=0;private timer=0;private generation=0;private busy=false;private tournaments:Tournament[]=[];private readonly ds:Array<()=>void>=[];
  public constructor(private readonly lobby:Node,private readonly api:CompetitionGateway,private readonly fail:(e:unknown)=>void){}
  public install():void{const button=this.button('btn_matchmaking','匹配 / 赛事',()=>void this.open(),190,48);button.setPosition(420,-315);this.lobby.addChild(button);this.on('aoo-competition-open',()=>void this.open());}
    public destroy():void{this.generation++;if(this.timer)globalThis.clearTimeout(this.timer);this.panel?.destroy();this.panel=null;if(isValid(this.lobby,true)&&(this.lobby as unknown as{_eventProcessor?:unknown})._eventProcessor)for(const d of this.ds.splice(0))d();else this.ds.length=0;}
  public async open():Promise<void>{if(!this.panel)this.build();this.panel!.active=true;this.render('LOADING','正在恢复权威状态…');const g=++this.generation;try{this.tournaments=await this.api.tournaments();const snapshot=await this.api.status(this.gameId);if(g!==this.generation)return;this.apply(snapshot,true);this.renderTournaments();this.poll(g);}catch(e){if(g===this.generation)this.error(e);}}
  private build():void{const panel=new Node('AooCompetitionPanel');panel.addComponent(UITransform).setContentSize(680,460);const title=this.label('title','快速匹配与赛事',30);title.setPosition(0,190);panel.addChild(title);const state=this.label('state','',24);state.setPosition(0,125);panel.addChild(state);this.statusLabel=state.getComponent(Label)!;const tournaments=this.label('tournaments','',20);tournaments.setPosition(0,25);panel.addChild(tournaments);this.tournamentLabel=tournaments.getComponent(Label)!;const queue=this.button('queue','开始匹配',()=>void this.queue(),150,48);queue.setPosition(-230,-170);panel.addChild(queue);const cancel=this.button('cancel','取消匹配',()=>void this.cancel(),150,48);cancel.setPosition(-75,-170);panel.addChild(cancel);const confirm=this.button('confirm','确认并入房',()=>void this.confirm(),170,48);confirm.setPosition(90,-170);panel.addChild(confirm);const signup=this.button('signup','报名 / 取消报名',()=>void this.toggleTournament(),190,48);signup.setPosition(265,-170);panel.addChild(signup);const close=this.button('close','关闭',()=>{panel.active=false;this.generation++;if(this.timer)globalThis.clearTimeout(this.timer);},100,42);close.setPosition(285,195);panel.addChild(close);this.lobby.addChild(panel);this.panel=panel;}
  private async queue():Promise<void>{if(this.busy)return;this.busy=true;this.render('QUEUEING','正在提交匹配…');try{this.apply(await this.api.queue(this.gameId,120));}catch(e){await this.recover(e);}finally{this.busy=false;}}
  private async cancel():Promise<void>{if(this.busy||!['WAITING','QUEUEING'].includes(this.state))return;this.busy=true;this.render('CANCELLING','正在取消…');try{this.apply(await this.api.cancel(this.gameId));}catch(e){await this.recover(e);}finally{this.busy=false;}}
  private async confirm():Promise<void>{if(this.busy)return;let s:MatchSnapshot;try{s=await this.api.status(this.gameId);}catch(e){return this.error(e);}if(!s.matchId)return;this.busy=true;this.render('CONFIRMING','正在确认席位…');try{this.apply(await this.api.confirm(s.matchId));}catch(e){await this.recover(e);}finally{this.busy=false;}}
  private async toggleTournament():Promise<void>{if(this.busy||this.tournaments.length===0)return;this.busy=true;const t=this.tournaments[0];try{if(t.status==='REGISTERED')await this.api.withdraw(t.tournamentId);else await this.api.register(t.tournamentId);this.tournaments=await this.api.tournaments();this.renderTournaments();this.lobby.emit('aoo-tournament-updated',this.tournaments);}catch(e){this.error(e);}finally{this.busy=false;}}
  private poll(g:number):void{if(g!==this.generation||!this.panel?.active)return;this.timer=globalThis.setTimeout(async()=>{try{const events=await this.api.events(this.cursor);if(g!==this.generation)return;for(const event of events)this.consume(event);this.poll(g);}catch(e){if(g===this.generation){this.render('RECOVERING','连接中断，正在恢复…');this.timer=globalThis.setTimeout(()=>this.poll(g),3000);this.lobby.emit('aoo-competition-recovering',e);}}},1500);}
  private consume(event:CompetitionEvent):void{this.cursor=Math.max(this.cursor,event.eventId);this.lobby.emit('aoo-competition-push',event);if(event.type.startsWith('TOURNAMENT_')){void this.refreshTournaments();return;}this.apply(event.payload as unknown as MatchSnapshot);}
  private async refreshTournaments():Promise<void>{try{this.tournaments=await this.api.tournaments();this.renderTournaments();}catch(e){this.error(e);}}
  private apply(s:MatchSnapshot,recovered=false):void{switch(s.state){case'WAITING':this.render('WAITING',`匹配中，游戏 ${s.gameId}…`);break;case'MATCHED':case'PENDING_CONFIRM':this.render('MATCHED','匹配成功，请在倒计时内确认');break;case'CONFIRMED':this.render('READY','房间已就绪，正在进入…');this.lobby.emit('aoo-competition-room-ready',{roomId:s.roomId,gameId:s.gameId,route:s.route,matchId:s.matchId});break;case'CANCELLED':this.render('CANCELLED','已取消匹配');break;case'TIMED_OUT':case'EXPIRED':this.render('TIMED_OUT','匹配已超时，可重新尝试');break;default:this.render('IDLE',recovered?'状态已恢复，可以开始匹配':'可以开始匹配');}this.lobby.emit('aoo-competition-state',{uiState:this.state,snapshot:s});}
  private async recover(cause:unknown):Promise<void>{this.render('RECOVERING','请求结果未知，正在查询权威状态…');try{this.apply(await this.api.status(this.gameId),true);}catch{this.error(cause);}}
  private error(e:unknown):void{this.render('ERROR',e instanceof Error?e.message:'赛事服务暂不可用');this.lobby.emit('aoo-competition-error',e);this.fail(e);}
  private render(state:UiState,text:string):void{this.state=state;if(this.statusLabel)this.statusLabel.string=text;}
  private renderTournaments():void{if(!this.tournamentLabel)return;if(this.tournaments.length===0){this.tournamentLabel.string='暂无可报名赛事';return;}const t=this.tournaments[0];this.tournamentLabel.string=`${t.name} · ${t.phase}\n${t.status==='REGISTERED'?'已报名，可取消':'未报名，可报名'}${t.rank?` · 排名 ${t.rank}`:''}`;}
  private label(name:string,text:string,size:number):Node{const n=new Node(name);n.addComponent(UITransform).setContentSize(620,90);const l=n.addComponent(Label);l.string=text;l.fontSize=size;l.lineHeight=size+6;l.color=Color.WHITE;l.horizontalAlign=Label.HorizontalAlign.CENTER;return n;}
  private button(name:string,text:string,click:()=>void,w:number,h:number):Node{const n=new Node(name);n.addComponent(UITransform).setContentSize(w,h);n.addComponent(Button);const t=this.label('Label',text,20);t.getComponent(UITransform)!.setContentSize(w,h);n.addChild(t);n.on(Button.EventType.CLICK,click);this.ds.push(()=>n.off(Button.EventType.CLICK,click));return n;}
  private on(name:string,fn:(v:unknown)=>void):void{this.lobby.on(name,fn);this.ds.push(()=>this.lobby.off(name,fn));}
}
