import type { AuthenticatedAccount } from './AuthTypes';
import { ProtocolHttpClient } from '../../../Common/Code/Runtime/network/ProtocolHttpClient';
import { resolveRuntimeEndpoints } from '../../../Common/Code/Runtime/config/RuntimeEndpoints';
import { httpGatewayUrl } from '../../../Common/Code/Runtime/network/GatewayEntryPolicy';
type OAuthProvider = { authorize(): Promise<string> }; type Json = Record<string, unknown>;

/** Commits a single-device credential session; NetworkRuntime remains the sole ticket/WSS owner. */
export class AooWeChatLoginController {
    private busy=false; private readonly aborts=new Set<AbortController>();
    public async login():Promise<AuthenticatedAccount>{if(this.busy)throw new Error('微信登录处理中');this.busy=true;try{
        const e=resolveRuntimeEndpoints();const tokens=await this.post('/api/v2/wechat/login',{code:await this.oauth().authorize(),deviceId:e.deviceId,channel:e.clientChannel,clientVersion:e.clientVersion,loginMode:'SINGLE_DEVICE'},{'X-Aoo-Api-Version':'1'});
        const account=await this.assemble(tokens);account.refreshWsTicket=()=>this.issueTicket(account);account.cancelWsTicketRequest=()=>this.cancelPending();return account;
    }finally{this.busy=false;}}
    public destroy():void{this.cancelPending();}
    private async assemble(tokens:Json):Promise<AuthenticatedAccount>{const e=resolveRuntimeEndpoints(),access=String(tokens.accessToken??''),refresh=String(tokens.refreshToken??'');if(!access||!refresh)throw new Error('微信登录未返回完整会话');const common=this.authHeaders(access),principal=await this.get('/api/v2/account/session',common),accountId=String(principal.accountId??'');if(!/^[1-9]\d*$/.test(accountId))throw new Error('微信会话账号无效');let profile:Json={};try{profile=await this.get('/api/v2/player-profile/me',common);}catch{/* optional */}const displayName=String(profile.nickname??profile.displayName??`玩家${accountId}`);return{accountId,account:`wechat:${accountId}`,displayName,deviceId:e.deviceId,accountToken:refresh,accessToken:access,refreshToken:refresh,accessExpiresAt:tokens.accessExpiresAt as string|number|undefined,refreshExpiresAt:tokens.refreshExpiresAt as string|number|undefined,accountType:2,openId:'',unionId:'',token:access,nickName:displayName,sex:Number(profile.sex??0),headImageUrl:String(profile.headImageUrl??''),profile};}
    private async issueTicket(account:AuthenticatedAccount):Promise<string>{try{return await this.issueTicketOnce(account);}catch(error:unknown){if(!(error instanceof HttpFailure)||error.status!==401||!account.refreshToken)throw error;const rotated=await this.post('/api/v2/account/token/refresh',{refreshToken:account.refreshToken},this.clientHeaders());account.accessToken=account.token=String(rotated.accessToken??'');account.refreshToken=account.accountToken=String(rotated.refreshToken??'');account.accessExpiresAt=rotated.accessExpiresAt as string|number|undefined;account.refreshExpiresAt=rotated.refreshExpiresAt as string|number|undefined;if(!account.accessToken||!account.refreshToken)throw new Error('微信会话刷新失败');account.onSessionRotated?.();return await this.issueTicketOnce(account);}}
    private async issueTicketOnce(account:AuthenticatedAccount):Promise<string>{const packet=await this.post('/api/v2/gateway/ws_ticket',{}, {...this.authHeaders(account.accessToken||account.token),'X-Idempotency-Key':this.key('wechat-ticket')}),ticket=String(packet.wsTicket??'');if(!ticket)throw new Error('网关未返回一次性连接票据');return ticket;}
    private authHeaders(access:string):Record<string,string>{return{Authorization:`Bearer ${access}`,...this.clientHeaders()};}
    private clientHeaders():Record<string,string>{const e=resolveRuntimeEndpoints();return{'X-Aoo-Api-Version':'1','X-Device-Id':e.deviceId,'X-Client-Channel':e.clientChannel,'X-Client-Version':e.clientVersion,'X-Page-Instance-Id':e.pageInstanceId};}
    private oauth():OAuthProvider{const p=(globalThis as typeof globalThis&{aooWeChatOAuth?:OAuthProvider}).aooWeChatOAuth;if(!p)throw new Error('微信 OAuth 生产适配器未安装');return p;}
    private get(path:string,headers:Record<string,string>):Promise<Json>{return this.request(path,'GET',undefined,headers);}private post(path:string,body:unknown,headers:Record<string,string>):Promise<Json>{return this.request(path,'POST',body,headers);}
    private async request(path:string,method:string,body:unknown,headers:Record<string,string>):Promise<Json>{const abort=new AbortController();this.aborts.add(abort);try{const response=await ProtocolHttpClient.fetch(httpGatewayUrl(path,resolveRuntimeEndpoints().apiBaseUrl),{method,signal:abort.signal,headers:{...this.clientHeaders(),...headers,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)}),packet=await response.json().catch(()=>({})) as Json;if(!response.ok||('code'in packet&&packet.code!=='OK'&&packet.code!==0))throw new HttpFailure(response.status,String(packet.message??packet.error??packet.code??`HTTP ${response.status}`));return(packet.data&&typeof packet.data==='object'?packet.data:packet)as Json;}finally{this.aborts.delete(abort);}}
    private cancelPending():void{for(const abort of this.aborts)abort.abort();this.aborts.clear();}private key(scope:string):string{return`client:${scope}:${globalThis.crypto?.randomUUID?.()??Date.now()}`;}
}
class HttpFailure extends Error{public constructor(public readonly status:number,message:string){super(message);}}
