import type { ProtocolClient } from '../network/ProtocolClient';
import { VoiceMediaClient,type ReadyVoice } from './VoiceMediaClient';
export interface VoiceView { recording(active:boolean):void; uploading(active:boolean):void; playing(assetId:number,active:boolean,durationMillis:number):void; error(code:string):void; }
export class RoomVoiceController {
  private disposed=false;private pending=false;private readonly off:()=>void;
  public constructor(private readonly roomId:string,private readonly seatId:number,private readonly protocol:ProtocolClient,private readonly media:VoiceMediaClient,private readonly view:VoiceView){this.off=protocol.on('room.voice',body=>void this.receive(body));}
  public async recordUploadSend():Promise<void>{if(this.pending||this.disposed)return;this.pending=true;this.view.recording(true);try{const recorded=await this.media.record();this.view.recording(false);if(!recorded||this.disposed)return;this.view.uploading(true);const ready=await this.media.upload(recorded);if(this.disposed)return;await this.protocol.request('room.voice',{action:'voice',roomId:this.roomId,seatId:this.seatId,assetId:ready.assetId});}catch(e){if(!this.disposed)this.view.error(e instanceof Error?e.message:'VOICE_SEND_FAILED');}finally{this.pending=false;this.view.recording(false);this.view.uploading(false);}}
  public destroy():void{if(this.disposed)return;this.disposed=true;this.off();this.media.cancel();this.view.recording(false);this.view.uploading(false);}
  private async receive(raw:unknown):Promise<void>{const v=raw&&typeof raw==='object'?raw as Record<string,unknown>:{};const reference=String(v.mediaId??v.url??'');const parsed=/^media:([1-9][0-9]{0,15})$/.exec(reference);const assetId=Number(v.assetId??parsed?.[1]);if(!Number.isSafeInteger(assetId)||assetId<=0)return;try{const ready=await this.media.describe(assetId);if(ready.state!=='READY'||ready.durationMillis<1||ready.durationMillis>60_000)return;this.view.playing(assetId,true,ready.durationMillis);try{await this.media.play(ready);}finally{if(!this.disposed)this.view.playing(assetId,false,ready.durationMillis);}}catch(e){if(!this.disposed)this.view.error(e instanceof Error?e.message:'VOICE_PLAY_FAILED');}}
}
