import { resolveRuntimeEndpoints } from '../config/RuntimeEndpoints';
import { ProductionApiError, type AccessTokenSource } from '../Activity/ProductionApiClient';
import { ProtocolHttpClient } from '../network/ProtocolHttpClient';
export interface AvatarUpload { bytes:ArrayBuffer;mimeType:'image/jpeg'|'image/png'|'image/webp';expectedVersion:number; }
interface Initiated {ticketId:string|null;assetId:number|null;chunkBytes:number;expectedParts:number;deduplicated:boolean;}
export class ProfileMediaGateway {private readonly controllers=new Set<AbortController>();private disposed=false;public constructor(private readonly token:AccessTokenSource,private readonly playerId:string){}
public async replaceAvatar(v:AvatarUpload,progress?:(sent:number,total:number)=>void):Promise<unknown>{if(!(v.bytes instanceof ArrayBuffer)||v.bytes.byteLength===0)throw new Error('头像文件为空');if(!Number.isInteger(v.expectedVersion)||v.expectedVersion<0)throw new Error('资料版本无效');const digest=await crypto.subtle.digest('SHA-256',v.bytes),sha256=Array.from(new Uint8Array(digest),x=>x.toString(16).padStart(2,'0')).join('');const started=await this.request<Initiated>('POST','/api/v2/player-profile/avatar/uploads',JSON.stringify({mimeType:v.mimeType,byteSize:v.bytes.byteLength,sha256}),'application/json');if(!started.deduplicated){if(!started.ticketId||started.chunkBytes<=0)throw new Error('上传票据无效');for(let n=1;n<=started.expectedParts;n++){const begin=(n-1)*started.chunkBytes,end=Math.min(v.bytes.byteLength,begin+started.chunkBytes);await this.request('PUT',`/api/v2/player-profile/avatar/uploads/${encodeURIComponent(started.ticketId)}/parts/${n}`,v.bytes.slice(begin,end),'application/octet-stream');progress?.(end,v.bytes.byteLength);}}return this.request('POST','/api/v2/player-profile/avatar/complete',JSON.stringify({ticketId:started.deduplicated?undefined:started.ticketId,assetId:started.deduplicated?started.assetId:undefined,expectedVersion:v.expectedVersion}),'application/json');}
public destroy():void{this.disposed=true;for(const c of this.controllers)c.abort();this.controllers.clear();}
private async request<T>(method:string,path:string,body:string|ArrayBuffer,type:string):Promise<T>{if(this.disposed)throw new Error('页面已关闭');const accessToken=(typeof this.token==='function'?this.token():this.token).trim();if(!accessToken)throw new ProductionApiError('SESSION_EXPIRED','登录会话已失效，请重新登录',401,false);const controller=new AbortController();this.controllers.add(controller);const c=globalThis.__aoo_RUNTIME_CONFIG__??{};try{const response=await ProtocolHttpClient.fetch(new URL(path.replace(/^\//,''),resolveRuntimeEndpoints().apiBaseUrl),{method,body,signal:controller.signal,headers:{Authorization:`Bearer ${accessToken}`,'X-Aoo-Api-Version':'1','X-Player-Id':this.playerId,'X-Device-Id':String(c.deviceId??'legacy-cocos-client'),'X-Client-Channel':String(c.clientChannel??'legacy-lobby'),'X-Client-Version':String(c.clientVersion??'3.8.8'),'Content-Type':type}});const packet=await response.json() as {code?:unknown;message?:unknown;data?:T};if(!response.ok||packet.code!=='OK')throw new ProductionApiError(String(packet.code??`HTTP_${response.status}`),String(packet.message??'头像更新失败'),response.status,response.status>=500);return packet.data as T;}finally{this.controllers.delete(controller);}}
}
