import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
test('create button uses canonical HTTPS room lifecycle and one in-flight request',()=>{
 const controller=read('assets/Modules/CreateRoom/Code/PlaySelectorController.ts');
 const gateway=read('assets/Lobby/Code/HallRoomGateway.ts');
 assert.match(controller,/const submittedRules = this\.presenter\.snapshot\(\);/);
 assert.match(controller,/gateway\.create\(selectedGame\.gameCode, submittedRules,/);
 assert.doesNotMatch(controller,/CBaseCreateRoom/);
 assert.doesNotMatch(controller,/CClubCreateRoom/);
 assert.match(controller,/implementedFamilies\.has\(this\.runtimeFamily\(game\.familyCode\)\)/);
 assert.match(gateway,/private pending: Promise<HallRoomHandoff> \| null/);
 assert.match(gateway,/\/api\/v2\/hall\/rooms/);
 assert.match(gateway,/\/ticket`/);
 assert.match(gateway,/deviceFingerprint: this\.deviceFingerprint\(\)/);
 assert.match(gateway,/该玩法当前不可用/);
 assert.doesNotMatch(gateway,/regionCode[^\n]*rooms/);
 assert.match(gateway,/scope: HallRoomScope/);
 assert.match(gateway,/clientVersion: '3\.8\.8', rules, scope/);
 assert.match(gateway,/public join\(roomId: number\)/);
 assert.match(gateway,/\/rooms\/\$\{roomId\}\/join/);
 assert.match(gateway,/public async refreshRoomConnection\(roomId: number\)/);
 assert.match(gateway,/return this\.issueRoomTicket\(roomId, room\.route\)/);
 assert.match(gateway,/private async issueRoomTicket\(roomId: number, fallbackRoute: string\)/);
 const joinController=read('assets/Lobby/Code/JoinRoomController.ts');
 const numpadService=read('assets/Common/Code/Runtime/ui/NumpadService.ts');
 const prefabMap=JSON.parse(read('assets/Common/Config/NativeMaps/prefab-path-map.json'));
 assert.match(joinController,/const FORM_PATH = 'common\/Numpad'/);
 assert.match(joinController,/gateway\.join\(Number\(roomKey\)\)/);
 assert.match(joinController,/this\.numpadService\.attach\(form\.node/);
 assert.match(numpadService,/Btn_Confirm/);
 assert.match(numpadService,/Btn_Digit\$\{value\}/);
 assert.equal(prefabMap['common/Numpad.prefab'],'native-ui/common/Numpad');
 assert.equal(prefabMap['ui/UIJoin.prefab'],undefined);
 assert.equal(prefabMap['ui/UIJoinMessage.prefab'],undefined);
 assert.match(joinController,/ROOM_KEY_DIGITS = 6/);
 assert.match(joinController,/\^\\d\{6\}\$/);
 assert.match(joinController,/{ title: '加入房间' }/);
 const successAt=joinController.indexOf("this.form.node.emit('authoritative-join-room-resolved'");
 const resetAt=joinController.lastIndexOf('this.resolving = false',successAt);
 assert.ok(resetAt>=0 && resetAt<successAt,'join single-flight guard must reset before scene handoff');
 assert.doesNotMatch(joinController,/digits\.length === 6\) void this\.resolveRoom/);
 assert.match(gateway,/roomId < 100000 \|\| roomId > 999999/);
 assert.doesNotMatch(joinController,/CBaseGetGameType/);
});
test('create-room handoff closes selector only after the authoritative room is ready',()=>{
 const controller=read('assets/Modules/CreateRoom/Code/PlaySelectorController.ts');
 assert.match(controller,/const selectedGame = this\.selectedGame;/);
 assert.match(controller,/const submittedRules = this\.presenter\.snapshot\(\);/);
 assert.match(controller,/gateway\.create\(selectedGame\.gameCode, submittedRules,/);
 const handoffAt=controller.indexOf('await this.onCreated({ ...handoff');
 const closeAt=controller.indexOf('if (this.forms.isAlive()) this.forms.close(FORM_PATH)',handoffAt);
 assert.ok(handoffAt>=0 && closeAt>handoffAt);
 const handoffBlock=controller.slice(handoffAt,controller.indexOf('} catch',handoffAt));
 assert.match(handoffBlock,/selectedGame\.gameId/);
 assert.match(handoffBlock,/selectedGame\.gameCode/);
 assert.doesNotMatch(handoffBlock,/this\.selectedGame\./);
 const lifecycleGuardAt=controller.indexOf('if (!node.isValid) return;');
 const componentLookupAt=controller.indexOf('node.getComponent(UITransform)',lifecycleGuardAt);
 assert.ok(lifecycleGuardAt>=0 && componentLookupAt>lifecycleGuardAt,
  'late DOM click must fail closed before reading components from a scene-destroyed button');
 assert.match(controller,/if \(!this\.forms\.isAlive\(\) \|\| !form \|\| !form\.node\.isValid\) return;/,
  'finally must not query a button owned by the destroyed lobby scene');
});
test('authoritative handoff carries room version route, native resources and one-time ticket',()=>{
 const gateway=read('assets/Lobby/Code/HallRoomGateway.ts');
 for(const field of ['roomId','gameId','playVersion','authorityRoute','gameTicket','bundleName','sceneName']) assert.match(gateway,new RegExp(field));
 const screen=read('assets/Lobby/Code/LobbyScreenController.ts');
 assert.match(screen,/this\.account\.deviceId\?\.trim\(\)/);
 assert.doesNotMatch(screen,/local-development-device/);
 const auth=read('assets/Login/Code/Auth/UnifiedIdentityAuthGateway.ts');
 assert.match(auth,/deviceId = resolveRuntimeDeviceId\(\)/);
 assert.match(auth,/resolveRuntimeEndpoints\(\)/);
 assert.match(auth,/displayName, deviceId, accountToken/);
 assert.match(screen,/open-authoritative-subgame/);
 assert.match(screen,/CommonPdkGameSceneLauncher/);
 assert.match(screen,/enterAuthoritativeSubgame/);
 const protocol=read('assets/Common/Code/Runtime/network/ProtocolClient.ts');
 const switcher=read('assets/Games/Poker/PDK/Common/Code/Runtime/CommonPdkSwitchCoordinator.ts');
 const launcher=read('assets/Games/Poker/PDK/Common/Code/Runtime/CommonPdkGameSceneLauncher.ts');
 assert.match(protocol,/bindRoomAuthority\(roomId:/);
 assert.match(protocol,/endsWith\('\.dispatch'\)/);
 assert.match(switcher,/gameClient\.setWsTicket\(gameTicket\)/);
 assert.match(switcher,/gameClient\.bindRoomAuthority\(roomId, playVersion\)/);
 assert.match(switcher,/await gameClient\.connect\(authorityRoute\)/);
 assert.match(switcher,/refreshRoomConnection\(roomId\)/);
 assert.match(switcher,/gameClient\.updateReconnectEndpoint\(refreshed\.authorityRoute\)/);
 assert.match(switcher,/gameClient\.setReconnectAuthenticator\(async \(\) => undefined\)/);
 assert.match(switcher,/playFamily === 'poker:pao-de-kuai' \|\| playFamily === 'poker-pao-de-kuai'/);
 assert.doesNotMatch(switcher,/playFamily[^\n]*=== 'pao-de-kuai'/);
 assert.match(launcher,/assetManager\.loadBundle\(bundleName/);
 assert.match(launcher,/director\.preloadScene\(sceneName/);
 assert.match(launcher,/director\.loadScene\(sceneName/);
 assert.match(launcher,/createDomStartupMask/);
 assert.match(launcher,/aoo-startup-dom-mask/);
 assert.match(launcher,/showDomStartupMask/);
 assert.match(launcher,/releaseDomStartupMask/);
 assert.match(launcher,/captureCanvasFrame/);
 assert.match(launcher,/isBlankCanvasFrame/);
 assert.doesNotMatch(launcher,/if \(!snapshot\) return null/);
 assert.match(launcher,/backgroundColor: '#041522'/);
 assert.match(launcher,/if \(snapshot\) root\.style\.backgroundImage/);
 assert.match(launcher,/waitForRoomBasePresentation/);
 assert.match(launcher,/waitForBaseLayers\(1_200\)/);
 assert.match(launcher,/房间基础界面未完成绘制，请重试/);
 assert.doesNotMatch(launcher,/mask\.root\.style\.opacity = '0'/);
 assert.match(launcher,/afterBrowserPaint/);
 assert.match(launcher,/await this\.showDomStartupMask\(retainedDomMask\)[\s\S]*this\.stage\('mount-room-runtime', this\.mount\(ticket, sceneName\)\)[\s\S]*await this\.releaseDomStartupMask\(retainedDomMask\)/);
 assert.doesNotMatch(launcher,/addPersistRootNode|removePersistRootNode/);
 assert.doesNotMatch(launcher,/ProgressBar|ProgressTrack|ProgressPercent|new Node\('Startup/);
 assert.doesNotMatch(launcher,/background: '#101821'/);
 assert.doesNotMatch(launcher,/bundle\.loadScene\(sceneName/);
 assert.doesNotMatch(launcher,/bundleName\s*=\s*['"]poker01-prefab|sceneName\s*=\s*['"]GameRoom2D/);
 const liveEnter=switcher.slice(switcher.indexOf('public async enter(ticket'),switcher.indexOf('public async enterReplay'));
 const connectAt=liveEnter.indexOf('await gameClient.connect(authorityRoute)');
 const preparationAt=liveEnter.indexOf('gameClient.setReconnectPreparation');
 const authenticatorAt=liveEnter.indexOf('gameClient.setReconnectAuthenticator(async () => undefined)');
 assert.ok(connectAt >= 0 && preparationAt > connectAt,
  'room reconnect preparation must be installed after connect(), because connect() clears old callbacks');
 assert.ok(authenticatorAt > preparationAt,
  'room reconnect must have an authenticator marker so socket close enters reconnect flow');
 assert.doesNotMatch(liveEnter,/room\.CBaseGameTypeUrl|base\.C1110UUID/);
});
